# -*- coding: utf-8 -*-
"""Atividade 3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IHP4hmyn-Zhk_Y6cVZiZ44gC7gHD4FgY

1) Crie um vetor com 5 elementos do tipo texto.
"""

Cachorros = ['Pitbull', 'Dobermann', 'Beagle', 'Yorkshire', 'Shih tzu']
print(Cachorros)

"""2) Imprima o nome que está na posição 2."""

print(Cachorros[2])

"""3) Imprima todos os nomes que estão no vetor."""

print(Cachorros)

"""4) Remova o item na posição 3 da sua lista."""

Cachorros.remove('Yorkshire')
print(Cachorros)

"""5) Acrescente o nome “Dime” na sua lista e depois faça sua remoção usando a função remove()."""

Cachorros.append('Dime')
print(Cachorros)

Cachorros.remove('Dime')
print(Cachorros)

"""6) Escreva uma função que receba dois números e retorne a soma deles."""

def funcaoSoma(num1, num2,):
  resultado = num1 + num2
  return resultado

funcaoSoma(5, 5)

"""7) Escreva uma função que receba uma lista de números e retorne o maior deles."""





"""8) Escreva uma função que receba 2 notas de um aluno, calcule sua média e retorne se ele foi aprovado ou não, considere aprovados com nota igual ou superior a 7."""

def notafinal(num1, num2):
  media = num1 + num2
  resultado = media / 2
  if resultado >= 7 :
    return "Aprovado"
  else:
      return "Reprovado"

notafinal(6, 6)

"""9) Crie uma função que receba o tempo em minutos e informe quantas horas tem nele."""

def horas(num1):
  resultado = num1 / 60
  print("São", resultado, "horas")

horas(120)

"""10) Crie uma função que receba um número e retorne seu sucessor+1 e antecessor+1."""

def natural(num1):
  sucessor = num1 + 1
  sucessor2 = sucessor + 1
  antecessor = num1 - 1
  antecessor2= antecessor -1
  return sucessor2, sucessor, antecessor, antecessor2

natural(24)